{% set name = "xtensor-r" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xtensor-stack/xtensor-r/archive/{{ version }}.tar.gz
  sha256: 0097524fb59b11d87560e9310195d06ea93242883384ebd35aec5b7ca4391fcf

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
  host:
    - xtl >=0.8,<0.9
    - xtensor >=0.26.0,<0.27
    - r-base
    - r-rcpp
  run:
    - {{ pin_compatible('xtl', max_pin='x.x') }}
    - {{ pin_compatible('xtensor', max_pin='x.x') }}
    - r-base

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-r  # [unix]
    - test -f ${PREFIX}/include/xtensor-r/rarray.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-r/xtensor-rConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-r/xtensor-rConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xtensor-r\rarray.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-r\xtensor-rConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-r\xtensor-rConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/xtensor-stack/xtensor-r
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: R bindings for xtensor, the C++ tensor algebra library
  description: Multi dimensional arrays with broadcasting and lazy computing
  doc_url: https://xtensor-r.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xtensor-r

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - davidbrochart
    - conda-forge/xtensor
