{% set name = "xtensor-r" %}
{% set version = "0.12.1" %}
{% set sha256 = "06cf5c6587d72a82dff98e63f1340c18302669a0337758495f176b80ffdf2acc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xtensor-r/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - xtl >=0.6.9,<0.7
    - xtensor >=0.21.2,<0.22
    - r-rcpp >=1.0.0,<1.1.0
  run:
    - {{ pin_compatible('xtl', max_pin='x.x') }}
    - {{ pin_compatible('xtensor', max_pin='x.x') }}
    - {{ pin_compatible('r-rcpp', max_pin='x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-r  # [unix]
    - test -f ${PREFIX}/include/xtensor-r/rarray.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-r/xtensor-rConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-r/xtensor-rConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor-r\rarray.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-rConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-rConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: R bindings for xtensor, the C++ tensor algebra library
  description: Multi dimensional arrays with broadcasting and lazy computing
  doc_url: http://xtensor-r.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-r

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
