appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: W9z7jkQiY/q9PNZInt1h7wDVCzc/Q03uM2IHr1sp4C9H4znUI8ZHQWBEZMl5gB9B6ZAbZ/kUZBZAzpLDbYKtsdfml+A1TIANjHAcB9SRaJQJqgVPf9yMcp8Bv0Tam9f0Uxi+AaXHlJbpsYXJyiC6a6mq2/zeMcHRtS0bfcX7Ts+0roAgGv1hQYkyZEiI+tMfnKly8mU5qmAEC0TeUb4ZDR9TIAqN39jH4UPGsUfm4GoVkalukgz1UxQnSu3N7I0CAMeqwotwrGu5h6b9NC1lQBxVKwBFBzeKr99UPIfIMk9EmLql0QDC00m/6J7TnCYvaED8ms2emKu6yaSJSpEn7n5jS+Vo+95N393UR9zHXaVfVEcYUXshtAdnWrLkLF1p50kTOEIoztZEEKOxSxl5HwFH8o7x3S5XvyPHwBXQdBEcwbBN9wsospXzjGDoCdSne+woyovHYkKtam9U2P0JHPEytW6C1v9ym8ugaHVTjEoVCxZfuo5acEvNH9GFE9B351Wzp92Dsg04E2Fz3UTU9RmD1o9rNqElnIQCzlGgcZpMkl+azVAYrTUVRbv0wnWtgjoR5l4ySiVKb4IiGp1SAGgBs8Hj+Z4vYqkSyAKusr0aA6kTycPrmQaSI45TdXMpBWCeGrJyQpOMljaWFlJQ+lXJHFM4jY/qmnwwdf36Ey8=}
